langauge: java

jdk:
- oraclejdk8

install: echo 'Skipping mvn install'

before_script:
- chmod a+x dch
- chmod a+x builddebian
- echo "MAVEN_OPTS='-Xmx2g -Xms1g'" > ~/.mavenrc

script:
- mvn clean verify -Declipse.p2.mirrors=false -Dtycho.localArtifacts=ignore

after_success:
- "./builddebian"

deploy:
  provider: s3
  access_key_id: AKIAIP5DWIO35XB7JNWA
  secret_access_key:
    secure: kWuZ7J7w/uzSVvPxh6Aodx1iNULy042+gDDX650BoAIvrBfQTOp9dWgJJTX3AMBicNLXfXXsl8XGiV1AOErMWgXiyW3RV2PqBSkW3W0HpHjSfovL2DjtfmxXVqyHWl2utW7aSrfKgFImqlEBwjklDfi2EEJDtv3Q3aCSjclyOc7WvER/5O3sQosD13OXL9vWPRTiLgJttzC6QqygSWkCxXAamwaBn1eebw3hF6CIooqOiT2O/BHBipNz5CGVV4LYGcI3qmAKFE81IBG/EDTjKTDmP5bJAglGHsRsPkeSkC1E3I3b6kCLr86IhAVQlAmLUczBG4njyOREykzrk1w2oQHoKx7GAsuAG4ZThUbS6bQbsgVV7SmtCfuTihrpCdbxweE5XePonyvzpbEVlfkr0QYHrwxG4XNc5cQ06i7B9D2PO2hFXegvnhirqFGed1zV+Qynor6SnUBjTXTD6Qulhf6K8eS5w5Z5CpLBmI7hx1uw7Hsx+bLscOo7mnRXCIIzHu0MDxWHXhFFFN5VsGVO8oZojsrdoJaTnmgNuFkZ6lfI2ofJ2X19OOZo94ixi0Unzl3TTgDdmtb/obUPGpK185gjEUxd8sG8H80N50yU7B0plEBdpzd4c5dpr4ExaIYlu5mfJYsBiKqTRx9CeNdsdHtWOMfc5SXGJsUlIYY1oEU=
  bucket: download.controlsystemstudio.org/debian/
  on:
    repo: ControlSystemStudio/org.csstudio.scanserver.product
