# whitelist

langauge: java

jdk:
  - oraclejdk8

install: echo 'Skipping mvn install'

before_script:
 - echo "MAVEN_OPTS='-Xmx2g -Xms1g'" > ~/.mavenrc

script:
 - mvn clean verify -Declipse.p2.mirrors=false -Dtycho.localArtifacts=ignore; ./builddebian

