#!/bin/bash
set -x

cp -R repository/target/products/scan-server/linux/gtk/x86_64/scan-server-* root/scanserver
cp root/scanserver_exec root/scanserver/scanserver
chmod a+x root/scanserver/ScanServer
chmod a+x root/scanserver/scanserver
cd root
./dch -i "${TRAVIS_COMMIT}"
./dch -r "${TRAVIS_COMMIT}"
git commit -m "${TRAVIS_COMMIT} [ci skip]" -- debian/changelog
git push origin HEAD:master
dpkg-buildpackage -rfakeroot -d -us -uc -i -I
