#!/bin/sh -e


case "$1" in
  configure)
    
    if ! getent passwd scanserver > /dev/null 2>&1; then
      useradd -c 'scanserver' -r -U scanserver
    fi 
    chown -R scanserver /usr/share/scanserver
    service scanserver restart 
    ;;
  abort-upgrade)
    :
    ;; 
  abort-remove)
    :
    ;; 
  abort-deconfigure)
    :
    ;; 
  *) echo "$0: didn't understand"
     exit 0
    ;;
esac
exit 0 
